name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installation
      run: g++ -std=c++17 -I/usr/include/gtest -L/usr/lib/x86_64-linux-gnu main.cpp -o program.out -lgtest -lpthread
    - name: make
      run: make
    - name: execute
      run: ./program.out
